### ISSUE TITLE
Add description that OTN slice for VN type 1 is not included

### ISSUE THREAD

**Issue by aguoietf** [aguoietf/ietf-ccamp-yang-otn-slicing#7]
Just VN type 2 of representing an OTN slice as an abstract topology

**Comment by sergiobelotti** [comment]
I think we should explain here the reason to adopt VN type 2 and not only VNtype 1. In my view the main reason is to permit the basic slicing feature of "resource reservation" that would result impossible without a minimum topology . Since VN type 1 is "a higher abstraction" of a type 2 VN slicing requirement impose some restriction to the level of possible abstraction.

**Comment by sergiobelotti** [comment]
Regarding this issue I tried to propose some text , attached in the draft update. 
[draft-zheng-ccamp-yang-otn-slicing-sb-070121.docx](https://github.com/aguoietf/ietf-ccamp-yang-otn-slicing/files/6748317/draft-zheng-ccamp-yang-otn-slicing-sb-070121.docx)
